apiVersion: skaffold/v2beta29
kind: Config

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*.yaml

build:
  local:
    push: false
  artifacts:
    - image: manvith507/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: manvith507/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.{js,jsx,ts,tsx,css,scss,sass,json}'
            dest: .
          - src: 'public/**/*'
            dest: .