# name: deploy

# on:
#     push:
#         branches:
#             - master
#         paths:
#             - "infra/**" # Only trigger workflow when files in infra/ change

# jobs:
#     auth-service:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v2
#             - uses: digitalocean/action-doctl@v2
#               with:
#                   token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

#             - run: doctl kubernetes cluster kubeconfig save ticketing-cluster

#             - run: kubectl apply -f infra/k8s/ && kubectl apply -f infra/k8s-prod/

#             # add secrets jwt and stripe_key -> can be added directly in server of cluster
#             # - run: |
#             #     kubectl create secret generic jwt-secret --from-literal=JWT_KEY=${{ secrets.JWT_KEY }}
#             #     kubectl create secret generic stripe-secret --from-literal=STRIPE_KEY=${{ secrets.STRIPE_KEY }}

#             # also need ingress nginx controller in the cluster -> can be done using that docs
#             #  kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/cloud/deploy.yaml
