name: deploy-manifest

on:
    workflow_dispatch: # This allows you to manually trigger the workflow from the GitHub Actions UI

    # on:
    # push:
    #     branches:
    #         - master
    #     paths:
    #         - "infra/**" # Only trigger workflow when files in infra/ change
jobs:
    auth-service:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2 # Checkout code from the repository
            - uses: digitalocean/action-doctl@v2 # Use DigitalOcean's CLI to manage the cluster
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} # Secret for DO access token

            - run: doctl kubernetes cluster kubeconfig save ticketing-cluster # Set kubeconfig for cluster

            - run: kubectl apply -f infra/k8s/ && kubectl apply -f infra/k8s-prod/ # Apply the k8s manifests

            # Add JWT and Stripe keys as secrets to the Kubernetes cluster
            - run: |
                  kubectl create secret generic jwt-secret --from-literal=JWT_KEY=${{ secrets.JWT_KEY }}
                  kubectl create secret generic stripe-secret --from-literal=STRIPE_KEY=${{ secrets.STRIPE_KEY }}

            # Deploy the Ingress Nginx controller to the Kubernetes cluster
            # Refer to the docs for more details on the Nginx Ingress Controller configuration
            - run: |
                  kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/cloud/deploy.yaml
