# name: deploy

# on:
#     push:
#         branches:
#             - master
#         paths:
#             - "auth/**" # Only trigger workflow when files in auth/ change

# jobs:
#     auth-service:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v2
#             # make the image push to docker hub and then deploy to kubernetes cluster
#             # need to add docker username password to git for access - secrets
#             - run: cd auth && docker build -t manvith507/auth .

#             - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#               env:
#                   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#                   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

#             - run: docker push manvith507/auth

#             - uses: digitalocean/action-doctl@v2
#               with:
#                   token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

#             - run: doctl kubernetes cluster kubeconfig save ticketing-cluster

#             - run: kubectl rollout restart deployment/auth-depl
